#\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password: 123
mybatis:
#\u6620\u5C04\u6587\u4EF6\u5168\u8DEF\u5F84
  mapper-locations: classpath:com/qf/dao/mapper/*.xml
#\u522B\u540D\u626B\u63CF
  type-aliases-package: com.qf.entity


